
export const COLOR_D1 = '#96A3AD';
export const COLOR_D2 = '#6B7780';
export const COLOR_D3 = '#424E57';
export const COLOR_D4 = '#1D2830';

export const COLOR_D5 = '#313A40';
export const COLOR_D6 = '#071218';
export const COLOR_D7 = '#000C14';

export const COLOR_WHITE = '#FFFFFF';
export const COLOR_BLACK = '#000000';

export const BACKGROUND_LIGHT = 'dedecd';
export const BACKGROUND_CONTROLS = COLOR_WHITE;
export const BORDER_CONTROLS = '#d4d4d4';


export const DARK_MODE = {
  COLOR1: COLOR_D1,
  COLOR2: COLOR_D2,
  COLOR3: COLOR_D3,
  COLOR4: COLOR_D4,

  COLOR5: COLOR_D5,
  COLOR6: COLOR_D6,
  COLOR7: COLOR_D7,

  TEXT_COLOR: COLOR_WHITE,
  PAGE_BACKGROUND: COLOR_D6,
  CONTROL_BACKGROUND: COLOR_D4,
  HEADER_BACKGROUND: COLOR_D4,
  LINK_COLOR: '#91ADD4',
  SUCCESS_COLOR: '#2FDF75',
  ALERT_COLOR: '#FF4961'
};
